### ISSUE TITLE
Not necessary to cache GHU transients

### ISSUE THREAD

**Issue by afragen** [WordPress-Phoenix/wordpress-rest-cache#17]
GHU now essentially post-processes all of it's `wp_remote_get()` responses and saves these to it's transients. It would seem that using the REST cache for these `wp_remote_get()` calls would be efficient but that using the hooks to override the setting and getting of GHU transients would become much less efficient.

It would seem that hooks `ghu_always_fetch_update` and `ghu_use_remote_call_transients` may no longer be useful.

I'm testing locally by commenting out https://github.com/WordPress-Phoenix/wordpress-rest-cache/blob/master/inc/class-wrc-filters.php#L33

What I expect to find is that REST cache gets the data as designed and when the transient expires a valid call to the database for the REST cache response will be done. The GHU transient will then be created and saved. GHU with then continue to use it's own transient until expiration and upon expiration will refresh from the REST cache database table.

**Comment by afragen** [comment]
In my testing both locally and on server this seems to work as I expected above. I will likely remove these filters from GitHub Updater unless there's some compelling reason to keep them.

Any thoughts @scarstens @mlteal ?

Actually only for `ghu_use_remote_call_transients` I see the use for `ghu_always_fetch_update`.

**Comment by scarstens** [comment]
Andy, right now, whatever changes have been made since we worked on the plugins together, have broken the process. Releasing with GHU is currently not a viable solution given the number of releases we do a week and the failure rate of GHU actually finding updates. If you think its best to remove filters from your plugin, go forth. 

If you think you have perfectly optimized how GHU spends its time using wp_get_remote, you can simply pass args to disable wp_rest_cache so that the plugin never caches the remote calls. That said, I can still say that if you have 30-40 git repos, GHU does not properly handle fetching updates in a way that scales to dozens or hundreds of plugins without failing, but maybe you have figured something out I haven't seen yet. Some architecting would need to go into batching updates into groups as to not overwhelm either the server requesting them, or the API calls and API limits of github's API service.

**Comment by afragen** [comment]
It must have happened when I did the optimization of the transients being stored. Since I was no longer storing the `wp_remote_get` response but storing parsed data from the response.

In testing locally, if I comment out the wp_rest_cache table deleting 'github-updater' rows and run the refresh transients, the wp_remote_get calls are being pulled from wp_rest_cache, which is what I would expect.

How frequently is wp_rest_cache updating it's data? I would think that in a site that is hit frequent enough to trigger the wp-cron then wp_rest_cache would always have up to date data and the only time GHU is calling wp_remote_get is on the infrequent chance that the wp_rest_cache data is stale and hasn't updated or when the Refresh Cache is clicked.

At some point when you or @mlteal have the time I'd like to see from your end why there are problems.

**Comment by afragen** [comment]
Maybe I can introduce some randomness to the transient timeout say 6 to 18 hours.

**Comment by afragen** [comment]
Is there a specific transient expiration timeout that would help wp_rest_cache be more efficient?

**Comment by afragen** [comment]
> If you think you have perfectly optimized how GHU spends its time using wp_get_remote, you can simply pass args to disable wp_rest_cache so that the plugin never caches the remote calls. That said, I can still say that if you have 30-40 git repos, GHU does not properly handle fetching updates in a way that scales to dozens or hundreds of plugins without failing, but maybe you have figured something out I haven't seen yet. Some architecting would need to go into batching updates into groups as to not overwhelm either the server requesting them, or the API calls and API limits of github's API service.

I still think there's a place for wp_rest_cache here. GHU doesn't optimize the wp_remote_get calls so much as it optimizes the results of those calls and saves that as the transient. In https://github.com/afragen/github-updater/commit/25fa56c26f8914e262af8a6516a71889b35976e7 I've introduced some variability to the transient expiration so that each plugin will expire at a different, or potentially different, time. The exception is a call to dot org is cached for a 6 to 18 days. https://github.com/afragen/github-updater/commit/88bc84e25ece612205e385b389049b870730dcd9

I think using this method I'm able to batch plugins on different API request schedules.

What do you think?

**Comment by scarstens** [comment]
I think your idea of variability is fine, its probably the simplest way for you to handle transient resolution, except for the first time it pulls in all the repos, at which point its going to fail in scale with this model. A batching model would only allow it to pull a limited amount of data in 1 PHP thread / call. 

The other issues at hand, I'm not sure exactly why its not working anymore, but I do know that the reason we moved away from transients in the first place is because they are not "simple" when they are stored in advanced cache (memcache/redis) and because they are storing large amounts of data, especially when you have 30-40 plugins on github. You can't have large datasets loaded into the cache pipe on every pageload. This was one of the reasons we disabled transients in the wp_rest_cache plugin.

But, as I said before, go ahead and do whatever is best for the GHU plugin right now. Its already "not working" so theres not much to worry about while changing right now.

**Comment by afragen** [comment]
GitHub Updater no longer uses transients, data is stored directly in wp_options with a timeout variable. This plays nicer with advanced caching. Just wanted to update before closing.
